# **Lab1: R Data Structures (21 points)**

#### **WRITE YOUR NAME HERE**


---

**IMPORTANT**:
- Before starting the lab, save a copy to your google drive by navigating to `File > Save a copy in Drive` <br>
- Then rename the copied file `Lab#_LASTNAME_FIRSTNAME.ipynb` where # is the lab assignment number, LASTNAME is your last name, and FIRSTNAME is your first name.

<br>


**Instructions**: Complete the lab below.

- <font color=red>Tasks</font> indicated in red must be completed to receive credit
- Include all code for your work
- Include markdown cells with written answers explaining your work when prompted
- **NOTE: Your completed lab must be submitted to Canvas as a .ipynb file by the end of the lab session**
---

<br>

<br>






####<font color=red>Organized</font> (1 points)
* Answers should be organized in the following format for organization and readability

<br>

```
# 1.
This will be the code block to answer the first part of a task
```

1. This will be the text answer/explanation (if prompted) for the first task

<br>

```
# 2.
This will be the code block to answer the second part of a task in a separate code cell
```

2. This will be the text answer/explanation (if prompted) for the second task

<br>

Continue this format for the remaining subtasks


<br>

---

<br>








<br>




## Vectors and Matrices


####<font color=red>Task 1</font>  (1 point)

* Insert the number 5 at the end of `my_vector` in a code cell below WITHOUT using 1, 2, 3, or 4 in your code
* Print your output

Hint: Use the `c()` function.

In [1]:
# vector defined
my_vector <- c(1, 2, 3, 4)

In [2]:
# insert the number five in code below
my_vector <- c(my_vector, 5)
my_vector

[1] 1 2 3 4 5



<br>




#### <font color=red>Task 2</font>  (1 point)

* Insert a row  of `c(-1, -1)` at the top of `my_matrix`
* Print your output

Hint: Use the `rbind()` function.

In [3]:
# matrix defined
my_matrix <- matrix(c(1,2,3,4,5,6), nrow = 3, ncol = 2, byrow=TRUE)
my_matrix <- rbind(c(-1, -1), my_matrix)
my_matrix

[,1] [,2]
[1,] -1   -1  
[2,]  1    2  
[3,]  3    4  
[4,]  5    6



<br>




#### <font color=red>Task 3</font>  (1 point)
* Print the length of `my_vector`

In [4]:
# vector defined
my_vector <- c(1,3,5,3,2,5,6,7,8,9,3,1,2,4,3,6,8,9,0,4,3,5,3,2,3,5,6,4,1,1,2,3)

In [5]:
# find length of vector
length(my_vector)

[1] 32



<br>




#### <font color=red>Task 4</font> (1 point)
* Multiply `matrix1` by `matrix2` below using scalar multiplication (use the `*` symbol)
* Print the result

In [6]:
# matrices defined
matrix1 <- matrix(1:9, nrow=3)
matrix2 <- matrix(2:10, nrow=3)
matrix1
matrix2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [7]:
# multiply matrices
matrix1 * matrix2

[,1] [,2] [,3]
[1,]  2   20   56  
[2,]  6   30   72  
[3,] 12   42   90



<br>




#### <font color=red>Task 5</font> (1 point)
* Multiply `matrix1` by `matrix2` below using matrix multiplication (use the `%*%` symbol)
* Print the result

In [8]:
# matrices defined
matrix1 <- matrix(1:9, nrow=3)
matrix2 <- matrix(2:10, nrow=3)
matrix1
matrix2

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[,1] [,2] [,3]
[1,] 2    5     8  
[2,] 3    6     9  
[3,] 4    7    10

In [9]:
# matrix multiplication
matrix1 %*% matrix2

[,1] [,2] [,3]
[1,] 42    78  114 
[2,] 51    96  141 
[3,] 60   114  168



<br>




## Collecting Data

#### <font color=red>Task 6</font> (4 points)

* Collect data from your other group members
 * Name
 * Number of siblings
 * Pets ("Yes" or "No")
 * Name of one pet (if no pet, then use `NA`)
* Create 4 vectors for each of the variables (use variable names that are useful!)

If members of your group would not like to provide certain information, that is okay! Simply enter `NA` in their entry

In [10]:
names <- c("Dylan", "Isabel") 
num_Siblings <- c(2, 2) 
pets <- c("Yes", "Yes")
pet_Names <- c("Ekko", "Marco")

<br>

#### <font color=red>Task 7</font> (2 points)

* Bind the four vectors together into a dataframe and store as another variable [use `data.frame()`)]
* Summarize your dataframe using `summary()`

In [11]:
data <- data.frame(names, num_Siblings, pets, pet_Names)
data

names  num_Siblings pets pet_Names
1 Dylan  2            Yes  Ekko     
2 Isabel 2            Yes  Marco

<br>

#### <font color=red>Task 8</font> (1 point)

* Convert the Pets variable ("Yes" or "No") into a factor and store in your dataframe
* Use the `class()` function to show it is now a `factor`

In [12]:
factor(data$pets, levels = c("Yes", "No"))

[1] Yes Yes
Levels: Yes No

<br>

#### <font color=red>Task 9</font> (1 point)

* Using your dataframe, calculate the average number of siblings in your group? (Use the `$` to call the variable from the dataframe)

In [13]:
mean(data$num_Siblings)

[1] 2

## Dataframes

* R offers several built-in dataframes already loaded for you to use
* For this activity we will use the `mtcars` dataset containing information on different car models

* The goal of this portion of the lab is to create a new variable for this dataframe that represents the engine displacement per cylinder in cubic inches for each vehicle
* You may not know what displacement is (or maybe even cylinders), but it will suffice to know that values in the column named `disp` divided by values in the column named `cyl` will yield the appropriate quantity



<br>




#### <font color=red>Task 10</font> (1 point)

One fundamental principle of working with data is that you should never overwrite or change your original raw data
* Copy/Store the `mtcars` dataframe into another dataframe called `mtcars_lastname` (i.e. `mtcars_lastname <- mtcars`)
 * E.g., My dataframe would be `mtcars_hasenstab`

In [14]:
mtcars_Watson <- mtcars



<br>




#### <font color=red>Task 11</font> (1 point)

* View the first few lines of the dataframe using `head()`

In [15]:
head(mtcars_Watson)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1



<br>




#### <font color=red>Task 12</font> (1 point)

* Use R code to determine the number of rows (observations) and columns (variables) in the dataframe
* Print the result

In [16]:
dim(mtcars_Watson)

[1] 32 11

There are 32 rows and 11 cols.

#### <font color=red>Task 13</font> (2 points)

* Calculate engine displacement per cylinder and save it as a new variable `UnitEngine` in the `mtcars_lastname` dataframe
* Note displacement per cylinder is defined by `disp` divided by `cyl`

Hint: `mtcars_lastname$UnitEngine <- ...`

In [17]:
mtcars_Watson$UnitEngine = mtcars_Watson$disp / mtcars_Watson$cyl
head(mtcars_Watson)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb UnitEngine
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4    26.66667  
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4    26.66667  
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1    27.00000  
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1    43.00000  
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2    45.00000  
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1    37.50000

#### <font color=red>Task 14</font> (1 point)

* Confirm that the `UnitEngine` variable has been added to the `mtcars_lastname` dataframe using the `summary()` function
* Show the summary


In [18]:
summary(mtcars_Watson)

      mpg             cyl             disp             hp       
 Min.   :10.40   Min.   :4.000   Min.   : 71.1   Min.   : 52.0  
 1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8   1st Qu.: 96.5  
 Median :19.20   Median :6.000   Median :196.3   Median :123.0  
 Mean   :20.09   Mean   :6.188   Mean   :230.7   Mean   :146.7  
 3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0   3rd Qu.:180.0  
 Max.   :33.90   Max.   :8.000   Max.   :472.0   Max.   :335.0  
      drat             wt             qsec             vs        
 Min.   :2.760   Min.   :1.513   Min.   :14.50   Min.   :0.0000  
 1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89   1st Qu.:0.0000  
 Median :3.695   Median :3.325   Median :17.71   Median :0.0000  
 Mean   :3.597   Mean   :3.217   Mean   :17.85   Mean   :0.4375  
 3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90   3rd Qu.:1.0000  
 Max.   :4.930   Max.   :5.424   Max.   :22.90   Max.   :1.0000  
       am              gear            carb         UnitEngine   
 Min.   :0.0000  



<br>




#### <font color=red>Task 15</font> (1 point)

* Use the `mean()` function to calculate the average miles per gallon (`mpg`) of all of the cars in the dataset

In [19]:
mean(mtcars_Watson$mpg)

[1] 20.09062